### ISSUE TITLE
The update function of youtube-dl does not work properly.

### ISSUE THREAD

**Issue by mtujikawa** [oleksis/youtube-dl-gui#1]
The update function of youtube-dl does not work properly.

3kb of unhealthy youtube-dl will be downloaded.

**Comment by Technetium1** [comment]
The update URL needs to be changed. See https://github.com/MrS0m30n3/youtube-dl-gui/issues/484 resulting in https://github.com/MrS0m30n3/youtube-dl-gui/pull/486.

**Comment by Technetium1** [comment]
Maybe the Python version will get bumped to 3.9 for releases too...?

**Comment by mtujikawa** [comment]
Thank you for your relpy. I will change URL.

**Comment by oleksis** [comment]
> The update function of youtube-dl does not work properly.
> 
> 3kb of unhealthy youtube-dl will be downloaded.

See like @h3xpl01t say https://github.com/oleksis/youtube-dl-gui/issues/2#issuecomment-727641748 fix your problem for close the issue.
