### ISSUE TITLE
Broken Data Parsing

### ISSUE THREAD

**Issue by InteXX** [oleksis/youtube-dl-gui#100]
---

  - [x] **I think** my problem is **NOT** with **yt-dlp**
  - [x] I've **verified** and **I assure** that I'm running yt-dlg **1.8.3**
  - [x] **I assure** that I am using the latest version of **yt-dlp**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

#### If the problem occurs when downloading a URL please provide the full verbose output as follows:

1. Restart **yt-dlg**
1. Go to `Options > Extra` tab
2. Enable **Debug youtube-dl**
3. Go to `Options > Advanced` tab and **Clear** your log content
4. Try to download the URL
5. Copy the **whole** log content and insert it between the ``` part below

#### What operating system do you use ?
Windows 10

#### List of actions to perform to reproduce the problem:

  1. Download any video using the latest version of yt-dlp.
  2. Note the incorrect information in the lower section columns (ETA, Speed, etc.). This started occurring immediately after I updated yt-dlp last night.
  3. The latest version of yt-dlp seems to have altered the data output format from previous versions. Perhaps a minor parsing adjustment is in order.

#### What is the expected behaviour ?
Correctly parsed information in the lower section columns (ETA, Speed, etc.).

#### What happens instead ?
Incorrectly parsed information in the lower section columns (ETA, Speed, etc.).

---

**Comment by oleksis** [comment]
You can share the URL to reproduce the error in the output ?

**Comment by InteXX** [comment]
Looks like you got to it before I did 🙂
