### ISSUE TITLE
language

### ISSUE THREAD

**Issue by senolfndk** [oleksis/youtube-dl-gui#115]
can you add turkish language in app

**Comment by oleksis** [comment]
Yes any translation is welcome! The [Localization Guide](https://oleksis.github.io/youtube-dl-gui/localization_howto.html) show how make a request for new language support: 

Turkey | tr
-- | --

[Country, region, and language codes](https://support.microsoft.com/en-us/topic/country-region-and-language-codes-add36afe-804a-44f1-ae68-cfb9c9b72f8b)
