### ISSUE TITLE
Not Able To Download from Microsoft Store

### ISSUE THREAD

**Issue by jonathonchavez** [oleksis/youtube-dl-gui#128]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

#### What operating system do you use ?
Windows 10.0.19045 Build 19045

#### List of actions to perform to reproduce the problem:

  1. Go to https://apps.microsoft.com/store/detail/ytdlg/XP9CCFSWS911F5
  
![image](https://user-images.githubusercontent.com/62238493/221791329-3a52e9b9-0ab3-4a5f-8126-36a5a87cb6b5.png)

  2. Launch Windows Store thru magnet link
  
![image](https://user-images.githubusercontent.com/62238493/221791437-ffa8dba1-f525-496a-87fc-bc0067349255.png)

  3. Store will open to home page and not download page
  
![image](https://user-images.githubusercontent.com/62238493/221791545-817033ef-3e9c-40b7-aa93-464f0fbd88e1.png)

Alternatively:
 
  1. Open Windows Store
  2. Search for yt-dlg as is the webpage
  3. Store says no results found
  
![image](https://user-images.githubusercontent.com/62238493/221791698-ad2b5ece-a67b-427b-993d-5beb44efdc0c.png)

#### What is the expected behaviour ?
Windows store allows download

#### What happens instead ?
App cannot be found on windows store

No adblock or anti-trackers enabled. Is there a direct portable download available on this repo? Thanks!

**Comment by oleksis** [comment]
The app is in Revision in this days and will be available by region soon, you can download the same installer from the [GitHub repo](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.5/yt-dlg-20230224.1.msi) the MSI: https://github.com/oleksis/youtube-dl-gui/releases/download/v1.8.5/yt-dlg-20230224.1.msi

**Comment by jonathonchavez** [comment]
Thank you!

**Comment by oleksis** [comment]
The update is live in the Store: https://apps.microsoft.com/store/detail/XP9CCFSWS911F5

![image](https://user-images.githubusercontent.com/44526468/222015738-b83b84d5-3f55-4dee-aa6e-67ff67475363.png)

When you can check and is OK for you Region feel free to close the issue. Thanks for the feedback!

**Comment by jonathonchavez** [comment]
I imagine it will be ready in a few days for me. Thanks!
![image](https://user-images.githubusercontent.com/62238493/222040810-cca97e0a-ce18-41e2-9064-ce8177deceba.png)

**Comment by smmalmansoori** [comment]
Maybe this should be closed by now?

**Comment by oleksis** [comment]
@jonathonchavez You can confirm if this issue has been solved?

**Comment by smmalmansoori** [comment]
Yes. I did the following:

1. Viewed the app in the store
2.  Installed it
3. Clicked the gearbox then "Update" to download the CLI backend
4. Used it to download  a video from YT

So in the store it's viewable, installable, and functional :thumbsup:
