### ISSUE TITLE
Crashes on Linux (Ubuntu-based)

### ISSUE THREAD

**Issue by RDKRACZ** [oleksis/youtube-dl-gui#142]
### This may be caused by Wayland because using GDK_BACKEND=x11 walkarounds the issue
&NewLine;
<br/>
&NewLine;

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Crash report

---

```
% ./yt-dlg

(yt-dlg:44966): GLib-GIO-ERROR **: 17:46:23.870: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
zsh: trace trap (core dumped)  ./yt-dlg
```

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/oleksis/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

Pop os 22.04

**Comment by oleksis** [comment]
Can test the version 1.8.6 from the repository and share the steps you follow?
