### ISSUE TITLE
Crash on trying to open app

### ISSUE THREAD

**Issue by opusforlife2** [oleksis/youtube-dl-gui#150]
### Before going further

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.8.5**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report

---

#### What operating system do you use ?

Windows 7

#### List of actions to perform to reproduce the problem:

  1. Try to open the app.

#### What is the expected behaviour ?

The app should open.

#### What happens instead ?

Two different error popups.

First:

System error (Windows dialog) - The program can't start because api-ms-win-cre-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem.

^ This error usually shows for me when an app has Win10 as the minimum version. But I've read other issues and this doesn't seem to be the case here.

Second:

Fatal error detected (yt-dlg dialog) -

Error loading Python DLL.
"%appdata%\Local\Temp\[foldername]\python310.dll"
LoadLibrary: The specified module could not be  found.

^ This error doesn't make sense to me because I have Python 3.8 installed (the last version to support Win7), and yt-dlg has always worked before this.

Also, why is it looking for a DLL inside a temp folder?

**Comment by oleksis** [comment]
The `yt-dlg` binaries for Windows use [PyInstaller](https://pypi.org/project/pyinstaller/). The version 1.8.5  use Python 3.10 for 64 bit architecture 

If you want use your Python 3.8 , one option is install `yt-dlg` from [PyPI](https://pypi.org/project/yt-dlg/)

**Comment by oleksis** [comment]
`yt-dlg` from PyPI is compatible from Python 3.8 to Python 3.11

`pip install yt-dlg`
