### ISSUE TITLE
Wheel error on Ubuntu 22.04.03

### ISSUE THREAD

**Issue by robbah** [oleksis/youtube-dl-gui#167]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [ ] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [ ] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

Hello,

I want to run youtube--dl-gui on Ubuntu 22.04.03. But when i run the command after i downloaded the .whl file: `python3 -m pip install wxPython-4.1.1-cp39-cp39-linux_x86_64.whl` i get the following error:

`ERROR: wxPython-4.2.1a1-cp310-cp310-linux_x86_64-jammy.whl is not a valid wheel filename.`

I am running python 3.10 on my machine.

Can someone please help me? Since i have no experience in Python whatsoever.

Thank you!

**Comment by oleksis** [comment]
For Ubuntu you can install `yt-dlg` from the Store: https://snapcraft.io/yt-dlg

**Comment by oleksis** [comment]
If the issue was fixed, please feel free to closed.
