### ISSUE TITLE
How to install it on ubuntu 20.04?

### ISSUE THREAD

**Issue by insanitywanted** [oleksis/youtube-dl-gui#17]
Is there any easy to understand guide for installing this on Ubuntu 20.04

**Comment by oleksis** [comment]
> Is there any easy to understand guide for installing this on Ubuntu 20.04

You can follow the steps for [Debian 10](https://github.com/oleksis/youtube-dl-gui#using-pip3-on-debian-10) and the [Notes](https://github.com/oleksis/youtube-dl-gui#notes) is for Ubuntu 20.04

**Comment by insanitywanted** [comment]
I followed the steps. Is there something missing? Sorry I am annoying. I am just new to linux.
![issue7](https://user-images.githubusercontent.com/47140829/118385007-d1383180-b628-11eb-961a-4a6de79345b6.png)

**Comment by oleksis** [comment]
> ![issue7](https://user-images.githubusercontent.com/47140829/118385007-d1383180-b628-11eb-961a-4a6de79345b6.png)

Don’t worry, we can help. You use virtual environment and install the requirements?

1. [Create the virtual environment and activate](https://github.com/oleksis/youtube-dl-gui#setting-the-virtual-environment-and-activate)

2. Inside the virtual environment, [install requirements and yt-dlg](https://github.com/oleksis/youtube-dl-gui#install-wxpython--requirements-and-yt-dlg)

**Comment by oleksis** [comment]
@insanitywanted Can run the GUI too:

```bash
python3 -m youtube_dl_gui
```
