### ISSUE TITLE
Feature request: CLI backend switching in the GUI (youtube-dl & yt-dlp) 

### ISSUE THREAD

**Issue by WeLoveOleksis** [oleksis/youtube-dl-gui#19]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.4.0**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Feature request (request for a new functionality)

### Feature request (request for a new functionality)

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?
Windows 10

---

Please add option in the GUI to switch between CLI backends (youtube-dl and yt-dlp). <3

**Comment by oleksis** [comment]
@WeLoveOleksis If you liked the new functionality, you can show your support for the project by voting with a star ⭐️
