### ISSUE TITLE
s

### ISSUE THREAD

**Issue by ghost** [oleksis/youtube-dl-gui#21]
s

**Comment by oleksis** [comment]
You can use this link to [FFmpeg](https://www.reddit.com/r/ffmpeg/comments/916iy8/ffmpeg_useful_links/?utm_source=share)  

Download and unzip this [FFmpeg for Windows](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z) , Then you need add the executable **ffmpeg.exe** to the `PATH` environment variable of Windows 

I’m get the Note 📝 for add this feature in the future if possible 😉

**Comment by nicolaasjan** [comment]
> You can use this link to [FFmpeg](https://www.reddit.com/r/ffmpeg/comments/916iy8/ffmpeg_useful_links/?utm_source=share)
> 
> Download and unzip this [FFmpeg for Windows](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.7z) , Then you need add the executable **ffmpeg.exe** to the `PATH` environment variable of Windows
> 
> I’m get the Note memo for add this feature in the future if possible wink

And FFprobe is also needed, I believe.
