### ISSUE TITLE
Fail trying to run (building from sources) in Mageia 8

### ISSUE THREAD

**Issue by katnatek** [oleksis/youtube-dl-gui#31]
- [ x] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running yt-dlg **1.6.0**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [ x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x ] Bug report
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

#### What operating system do you use ?
Mageia Linux 8

#### List of actions to perform to reproduce the problem:

  1. .. Download source tarball
  2. .. Build a rpm
  3. .. Install the resulting rpm
  4. .. Run yt-dlg
  5. .. Get this error
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/youtube_dl_gui/app.py", line 65, in OnInit
    wx.Locale.AddCatalogLookupPathPrefix(locale_dir)
TypeError: Locale.AddCatalogLookupPathPrefix(): argument 1 has unexpected type 'NoneType'
OnInit returned false, exiting...
```
#### What is the expected behaviour ?

yt-dlg is launched correctly

#### What happens instead ?

Fail with the error mentioned
---
This is the spec file i use to build the rpm,  my distribution don't provide python3-altgraph so i make it and install
[youtube-dl-gui.spec.txt](https://github.com/oleksis/youtube-dl-gui/files/6718934/youtube-dl-gui.spec.txt)

 python3.8

**Comment by oleksis** [comment]
When you can try re-build from [Source (.zip)](https://github.com/oleksis/youtube-dl-gui/archive/v1.7.0.zip).
Remember before build you need generate and add the .mo files from locale folder for translations

Thanks for the report! 😉

**Comment by katnatek** [comment]
Build with 1.7.0 source, bow i get this
```
yt-dlg 
Traceback (most recent call last):
  File "/usr/bin/yt-dlg", line 33, in <module>
    sys.exit(load_entry_point('yt-dlg==1.7.0', 'console_scripts', 'yt-dlg')())
  File "/usr/bin/yt-dlg", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by oleksis** [comment]
> Build with 1.7.0 sources, now i get this
> 
> ```
> yt-dlg 
> Traceback (most recent call last):
>   File "/usr/bin/yt-dlg", line 33, in <module>
>     sys.exit(load_entry_point('yt-dlg==1.7.0', 'console_scripts', 'yt-dlg')())
>   File "/usr/bin/yt-dlg", line 25, in importlib_load_entry_point
>     return next(matches).load()
> StopIteration
> ```

You can open other issue for the second error (in the quotes) and describe the workflow/steps before to until you get this error. Thanks one more time!

**Comment by katnatek** [comment]
I think i miss some requires, i am working on that, when i finish i will comment my result.

**Comment by oleksis** [comment]
> I think i miss some requires, i am working on that, when i finish i will comment my result.

Ok any type of information will help fix the issue.

**Comment by katnatek** [comment]
I get it work but i still have to clean the spec file to see what is really necessary
For the moment i get it works with the system wxpython so i don't have to build again as with the recommended method (that fail me anyway :( )

I don't sure if must open other issue or comment in this one but 
at first run it downloads youtube-dl and install it on .config/yt-dlg/youtube-dl but without execute rights
[log-yt-dlg.txt](https://github.com/oleksis/youtube-dl-gui/files/6766392/log-yt-dlg.txt)

Once i `chmod a+x .config/yt-dlg/youtube-dl` the application works as must :)

**Comment by oleksis** [comment]
> Once i `chmod a+x .config/yt-dlg/youtube-dl` the application works as must :)

That issue will fix in the PR #36 set the permission execution on Linux. The next release will add that 😉

**Comment by katnatek** [comment]
> > Once i `chmod a+x .config/yt-dlg/youtube-dl` the application works as must :)
> 
> That issue will fix in the PR #36 set the permission execution on Linux. The next release will add that wink

Test the fix, works if the youtube-dl is not previously in the folder but if a youtube-dl with wrong rights is in the folder the bad behaviour persists ;)

**Comment by katnatek** [comment]
> > > Once i `chmod a+x .config/yt-dlg/youtube-dl` the application works as must :)
> > 
> > 
> > That issue will fix in the PR #36 set the permission execution on Linux. The next release will add that wink
> 
> Test the fix, works if the youtube-dl is not previously in the folder but if a youtube-dl with wrong rights is in the folder the bad behaviour persists ;)

Easy fix press on update so i release a new package for mageia that make the warning.

Thanks for all

**Comment by oleksis** [comment]
> Easy fix press on update so i release a new package for mageia that make the warning.

I’m glad for that. Have planned make oficial release for Mageia?. Share the link here the last Release updated if is possible.

Thanks too, and will in contact!

**Comment by katnatek** [comment]
> I’m glad for that. Have planned make oficial release for Mageia?. Share the link here the last Release updated if is possible.
> 
> Thanks too, and will in contact!

Not for the Official repositories but for the Repository of BlogDrake (https://blogdrake.net/), the community for Spanish Speaking users.

I put the instructions to add the repository and the application tomorrow (i hope)
