### ISSUE TITLE
Add .desktop file

### ISSUE THREAD

**Issue by jose1711** [oleksis/youtube-dl-gui#34]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Bug report

I think `.desktop` file should be added to source code.

**Comment by oleksis** [comment]
You can test this [commit ](https://github.com/oleksis/youtube-dl-gui/commit/effd7b72bf1cc4d37ab98dd745fe573a1eb1c292) Add yt-dlg.desktop in GNU/Linux

**Comment by jose1711** [comment]
> You can test this [commit ](https://github.com/oleksis/youtube-dl-gui/commit/effd7b72bf1cc4d37ab98dd745fe573a1eb1c292) Add yt-dlg.desktop in GNU/Linux

Thank you, that looks good. I guess localized entries (e. g. `name[XX]`) can later be added by translators.

**Comment by oleksis** [comment]
> Thank you, that looks good. I guess localized entries (e. g. `name[XX]`) can later be added by translators.

Yes, totally agree.  With the help of translators and the Community we can complete the translations as much as possible
