### ISSUE TITLE
groupby season

### ISSUE THREAD

**Issue by mahdisky** [oleksis/youtube-dl-gui#4]
hi
how to group by season folder?

**Comment by oleksis** [comment]
> hi
> how to group by season folder?

Depending on the Video/PlayList properties you can create a Template Path with the following structure:

```bash
youtube-dl [URL] -o '%(season)s/%(series)s - %(season_number)05d - %(title)s.%(ext)s'
```

**Comment by oleksis** [comment]
> hi
> how to group by season folder?

Using the GUI in Settings / Extra you can set the -o parameter also before downloading the URL
