### ISSUE TITLE
Clip multimedia buttons rendered incorrectly

### ISSUE THREAD

**Issue by jose1711** [oleksis/youtube-dl-gui#41]
### Before going further

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Bug report

Buttons in clip multimedia dialog window do not look OK.

![obrázok](https://user-images.githubusercontent.com/1406222/124367218-882e5200-dc55-11eb-83f9-814634dfbc53.png)

#### What operating system do you use ?

Arch Linux, x86_64, `wxpython '4.0.7.post2 gtk3 (phoenix) wxWidgets 3.0.5'`

**Comment by oleksis** [comment]
I test that issue before in Debian why in Linux `youtube_dl_gui.widgets.ClipDialog.FRAME_SIZE` change the size in case the platform.

You can share the version (commit) you test ClipDialog? Test the right property FRAME_SIZE ?

**Comment by jose1711** [comment]
I've retested with 9789d97 which is now the current HEAD and it's the same behaviour. `FRAME_SIZE` used is `(250, 170)`. One thing I noticed is this message in terminal window on execution:
```
00:40:02: Warning: Mismatch between the program and library build versions detected.
The library used 3.0 (wchar_t,compiler with C++ ABI 1014,wx containers,compatible with 2.8),
and wxPython used 3.0 (wchar_t,compiler with C++ ABI 1016,wx containers,compatible with 2.8).
```
Not sure if it's related. Then there's a lot of
```
(yt-dlg:76801): Gtk-CRITICAL **: 00:40:07.574: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(yt-dlg:76801): Gtk-CRITICAL **: 00:40:07.590: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(yt-dlg:76801): Gtk-CRITICAL **: 00:40:07.590: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(yt-dlg:76801): Gtk-CRITICAL **: 00:40:19.231: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton

(yt-dlg:76801): Gtk-CRITICAL **: 00:40:19.231: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```
