### ISSUE TITLE
yt-dlg from Releases doesn't work on Linux Mint 19.3

### ISSUE THREAD

**Issue by nicolaasjan** [oleksis/youtube-dl-gui#42]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.7.0**
  - [x] **I assure** that i am using the latest version of **yt-dlp**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

Please remove any sections between (---) if they are not related to your issue

When trying to run yt-dlg on Linux Mint 19.3 (based on Ubuntu 18.04), I get a dependency error:

```
./yt-dlg
Traceback (most recent call last):
  File "youtube_dl_gui/__main__.py", line 33, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "youtube_dl_gui/app.py", line 18, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: libjpeg.so.62: cannot open shared object file: No such file or directory
[1736] Failed to execute script __main__
```
When I installed that library , I got another error:

```
./yt-dlg
Traceback (most recent call last):
  File "youtube_dl_gui/__main__.py", line 33, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "youtube_dl_gui/app.py", line 18, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "wx/core.py", line 12, in <module>
ImportError: /tmp/_MEIHMstNG/libz.so.1: version `ZLIB_1.2.9' not found (required by /usr/lib/x86_64-linux-gnu/libpng16.so.16)
[2487] Failed to execute script __main__
```
I have `libz.so.1.2.11`

This is where I gave up and tried to [install the binary from source](https://github.com/oleksis/youtube-dl-gui#binaries).
After many failed attempts, that finally worked, but took a considerable amount of time...
(especially the building of `wxPython-4.1.1-cp36-cp36m-linux_x86_64.whl`)

I have a working executable now, but I'd like to know if there is a way to build faster when a new version will be released?
Is this somehow possible by using the already built wheel file again?
(saved it from `~/.cache`)

**Comment by oleksis** [comment]
The binary "bundle app" build for Linux is from [Many Linux 2014](https://github.com/oleksis/youtube-dl-gui/blob/9789d974ec44dd07275ed19cca39cfad6a9cd1f0/.github/workflows/release.yml#L71) which use [Docker image one version  CentOS 7](https://www.python.org/dev/peps/pep-0599/#id22) (glibc 2.17, ) and the shared libraries is pinned with a least the same version where was builded. 


If you check the [Notes](https://github.com/oleksis/youtube-dl-gui#notes) and try install wxPython 4 wheel for [you distro](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/) in the oficial website  the nexts release install from the source will make more easy 

If you find other way more easy or will like share your build workflow for your distro I can add to the README or the Wiki 🙏🏾

**Comment by nicolaasjan** [comment]
> If you check the [Notes](https://github.com/oleksis/youtube-dl-gui#notes) and try install wxPython 4 wheel for [you distro](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/) in the oficial website the nexts release install from the source will make more easy

Thanks!
I'm a bit confused now, because there are 4 different wheels listed there under `2020-11-25`.
Which one do I choose to install?

![Screenshot 2021-07-05 at 08-39-08 Index of wxPython4 extras linux gtk3 ubuntu-18 04](https://user-images.githubusercontent.com/14093220/124431362-8c9b5d80-dd70-11eb-9df7-e2cc5d1b3170.png)


Never mind, the one I already compiled (`wxPython-4.1.1-cp36-cp36m-linux_x86_64.whl`) is already installed in `~/.local/lib/python3.6/site-packages`
And it's working too, because the "Hello World" command works.
`python3 -c "import wx; a=wx.App(); wx.Frame(None,title='hello world').Show(); a.MainLoop();"`

![Schermafdruk op 2021-07-05 10-31-35](https://user-images.githubusercontent.com/14093220/124441722-42b87480-dd7c-11eb-97df-8ce38bcc7885.png)


When building yt-dlg again, it used that one and the compilation was way faster. :)

**Comment by oleksis** [comment]
> I'm a bit confused now, because there are 4 different wheels listed there under `2020-11-25`.
> Which one do I choose to install?
> 
You will install base the python version have by default or want use in your virtual environment for example [wxPython-4.1.1-cp36-cp36m-linux_x86_64.whl](https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-18.04/wxPython-4.1.1-cp36-cp36m-linux_x86_64.whl) 

I’m glad your find one way use wxPython for your distro. If is Ok feel free close the issue.
