### ISSUE TITLE
Add instructions to install on mageia 8

### ISSUE THREAD

**Issue by katnatek** [oleksis/youtube-dl-gui#43]
I make a changes to README.md to add instructions to install on mageia 8

I hope all is right , i am beginner on this

[README.md](https://github.com/oleksis/youtube-dl-gui/files/6779571/README.md)

**Comment by katnatek** [comment]
Sorry use this one
[README.md](https://github.com/oleksis/youtube-dl-gui/files/6779610/README.md)

**Comment by oleksis** [comment]
@katnatek I add the instruccions to install on mageia 8 [see commit](https://github.com/oleksis/youtube-dl-gui/commit/7b7fcaf06d8a151e2779fa0ca3bdafe7ba068f74) . You can update the package name a `yt-dlg` and the docs?

**Comment by katnatek** [comment]
> @katnatek I add the instruccions to install on mageia 8 [see commit](https://github.com/oleksis/youtube-dl-gui/commit/7b7fcaf06d8a151e2779fa0ca3bdafe7ba068f74) . You can update the package name a `yt-dlg` and the docs?

Sure i can do that, give me some time, what you mean with the docs?

**Comment by oleksis** [comment]
With the docs I mean, update the `README.md` with the changes and the steps the user follows for install `ya-dlg`

Take your time and thanks 🙏🏾

**Comment by katnatek** [comment]
> With the docs I mean, update the `README.md` with the changes and the steps the user follows for install `ya-dlg`
> 
> Take your time and thanks 🙏🏾

Done!
[README.md](https://github.com/oleksis/youtube-dl-gui/files/7228963/README.md)

**Comment by oleksis** [comment]
You can test the package for **mageia 8** and share the link to the spec and the rpm for use with other Distros?

**Comment by katnatek** [comment]
> You can test the package for **mageia 8** and share the link to the spec and the rpm for use with other Distros?

I test before edit the README  ;)
![yt-dlg on mageia 8](https://user-images.githubusercontent.com/49327072/134777910-cb126a4a-a7c6-4bfa-aaf6-6db1719e992b.png)

Not the spec but the src.rpm, it may require edit for other distros as have some mageia specific things https://ftp.blogdrake.net/mageia/mageia8/free/SRPMS/yt-dlg-1.7.2-0.git20210921bdk_mga8.src.rpm

Not sure if works for other distros but here is the rpm https://ftp.blogdrake.net/mageia/mageia8/free/noarch/yt-dlg-1.7.2-0.git20210921bdk_mga8.noarch.rpm

**Comment by katnatek** [comment]
Is not showing one step, please use the fixed README ;)
[README.md](https://github.com/oleksis/youtube-dl-gui/files/7230024/README.md)

**Comment by oleksis** [comment]
@katnatek Thanks very much. I will add the links and the changes to the README. 🙏🏾

**Comment by oleksis** [comment]
@katnatek README.md updated, if everything is ok and working on Mageia 8 fell free close de issue.

**Comment by katnatek** [comment]
> @katnatek README.md updated, if everything is ok and working on Mageia 8 fell free close de issue.

Closing, its ok if when new release is done i notify of updated links in this thread?  i try to remove old versions to save space

**Comment by oleksis** [comment]
> Closing, its ok if when new release is done i notify of updated links in this thread?  i try to remove old versions to save space

My advice is for new release try open new issue and update links, docs then the users have the options to see the changes and decide 💪🏾

Thanks for the docs collaboration 🙏🏾
