### ISSUE TITLE
How can we add different formats in the options settings?

### ISSUE THREAD

**Issue by stillpointx** [oleksis/youtube-dl-gui#5]
- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x ] **I think** my problem is **NOT** with **youtube-dl**
  - [x ] I've **verified** and **i assure** that I'm running youtube-dlg **1.0.0**
  - [x ] **I assure** that i am using the latest version of **youtube-dl**
  - [x ] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x ] Question
- [ ] Other

---
**How can we add different formats in the options settings?**

![screenshot-2021-01-23-05-09-44](https://user-images.githubusercontent.com/28985314/105575403-74430380-5d39-11eb-8053-fa36f2f32572.png)

**Comment by oleksis** [comment]
> **How can we add different formats in the options settings?**

Those formats are predefined by the interface (GUI) from the original version.  You can add more options (formats) in the Settings -> Extra section and add the parameters of [select Formats](https://github.com/ytdl-org/youtube-dl#format-selection) by lines
