### ISSUE TITLE
Version 1.7.1 Crash on Mageia

### ISSUE THREAD

**Issue by katnatek** [oleksis/youtube-dl-gui#50]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/ytdl-org/youtube-dl/issues)

- Make sure you are using the *latest* **yt-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [ x] I've **verified** and **i assure** that I'm running yt-dlg **1.7.1**
  - [ x] **I assure** that i am using the latest version of **youtube-dl**
  - [ x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [ ] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

Please remove any sections between (---) if they are not related to your issue

---

### Bug report
youtube-dlg not start, i got this on console

```
yt-dlg 
Traceback (most recent call last):
  File "/usr/bin/yt-dlg", line 33, in <module>
    sys.exit(load_entry_point('yt-dlg==1.7.1', 'console_scripts', 'yt-dlg')())
  File "/usr/bin/yt-dlg", line 25, in importlib_load_entry_point
    return next(matches).load()
StopIteration
```

**Comment by oleksis** [comment]
How you install `yt-dlg` from pip or the binary?

You can share the steps you follow for get that error?

**Comment by katnatek** [comment]
I use rpm build from source like in the 1.7.0 version (that version works)
The spec file
[youtube-dl-gui.spec.txt](https://github.com/oleksis/youtube-dl-gui/files/7188859/youtube-dl-gui.spec.txt)

**Comment by oleksis** [comment]
You can try run `yt-dlg` from Python 3 before the rpm version?

I will try make the rpm for openSUSE see is work. Make sure this work with the Python from the distribution.

**Comment by katnatek** [comment]
I see a package for alt-linux and except for split in two parts the package is the same i do, i don't know what broke the 1.7.1

**Comment by katnatek** [comment]
Interesting i make a test in the spec and it launch the application, but the final rpm fail, maybe some is not copy to final rpm i make some more test

**Comment by katnatek** [comment]
Testing with https://github.com/oleksis/youtube-dl-gui/commit/72702e190ac7b760bc05530938f25dce266d526a
It works, for the moment i release that version

**Comment by oleksis** [comment]
I'm glad that work. Is the version 1.7.2 thar require Python >= 3.7 . Planning keep update with the latest version of Python and make the code more maintainable.

When you make the release and test if work, feel free close the issue 🙏🏾

**Comment by katnatek** [comment]
Closed but don't like don't know what was the real issue :(

**Comment by katnatek** [comment]
Finally i found the possible cause, the old packages don't clean the python site-packages folder and that cause the issue, i fix that on the new release

**Comment by oleksis** [comment]
@katnatek Good to know! I will merge the update for the README.md 

If is possible the community help testing in distros like Mageia and openSUSE are welcome 🙏🏾
