### ISSUE TITLE
Other: translation

### ISSUE THREAD

**Issue by goYou** [oleksis/youtube-dl-gui#53]
If possible, can you provide a new translation team? The original translation team has not responded for a long time

**Comment by oleksis** [comment]
@goYou if you want collaborate with translations make a fork of this project and feel free to make a pull request. Thanks for the interest 🙏🏾

**Comment by goYou** [comment]
> @goYou if you want collaborate with translations make a fork of this project and feel free to make a pull request. Thanks for the interest 🙏🏾

Unable to join the original translation team, unable to obtain the glossary of the project, unable to generate translation files

**Comment by oleksis** [comment]
The lasts translations collaborations the users make from GitHub. The original project was stopped around 2018. 

Now my advice if you want collaborate is use the file `youtube_dl_gui/locale/en_US/LC_MESSAGES/youtube_dl_gui.po` like source for others translations

**Comment by goYou** [comment]
> The lasts translations collaborations the users make from GitHub. The original project was stopped around 2018.
> 
> Now my advice if you want collaborate is use the file `youtube_dl_gui/locale/en_US/LC_MESSAGES/youtube_dl_gui.po` like source for others translations

If possible, please provide new full documentationu. 🙂

**Comment by oleksis** [comment]
Thanks for the translation for China, you can test install GitHub

```bash
pip install git+https://github.com/oleksis/youtube-dl-gui.git
```

The next release (v1.8.0) will included

🙏🏾

**Comment by goYou** [comment]
Thank you for your continuous update. 🙂
If possible, can you modify the color scheme of the dark mode? I can’t give specific suggestions because I’m not good at UI. 😊

**Comment by goYou** [comment]
> Thanks for the translation for China, you can test install GitHub
> 
> ```shell
> pip install git+https://github.com/oleksis/youtube-dl-gui.git
> ```
> 
> The next release (v1.8.0) will included
> 
> ![yt-dlg_v1 8 0](https://user-images.githubusercontent.com/44526468/134941112-94a26d56-eb82-4698-b249-43f776d031dc.jpg)
> 
> 🙏🏾

Thank you for your continuous update. 🙂
If possible, can you modify the color scheme of the dark mode? I can’t give specific suggestions because I’m not good at UI. 😊
