### ISSUE TITLE
locale error when open program

### ISSUE THREAD

**Issue by linuxgirl22** [oleksis/youtube-dl-gui#62]
- [ ] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

### What is the purpose of your *issue*?

- [x] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

### Bug report
```
03:59:23: Cannot set locale to language "English (U.S.)".
03:59:23: locale 'en_US' cannot be set.
```

#### What operating system do you use ?
Just installed arch, running mate desktop (but am not very tech/just come from Mint). 

#### List of actions to perform to reproduce the problem:

  1. open the gui

#### What is the expected behaviour ?
selecting 'English' within settings wouldn't cause an error about locale

#### What happens instead ?
pop-up every time says locale 'en_US' cannot be set (am in UK)

I've tried opening settings.json, and the python file, changing en_US to en_UK, but it reverts when close yt-dlg-gui.  Log in .config is empty. 
Ran update, and the cli updated, but the pop-up still happens. 

locale -a ... 
C
en_GB.utf8
POSIX

Have checked /etc/locale.gen, and en_GB.UTF-8 UTF-8 is set

Thanks for including yt-dlp as a backend, too.

**Comment by oleksis** [comment]
You can provide more information (screenshots, Logs ...) or sequences of steps for reproduction the error ?

**Comment by linuxgirl22** [comment]
Thanks for your response, oleksis :-) No issue now.
