### ISSUE TITLE
Please update README.md

### ISSUE THREAD

**Issue by katnatek** [oleksis/youtube-dl-gui#71]
I update the mageia package and the previous packages were deleted please update the README.md
[README.md](https://github.com/oleksis/youtube-dl-gui/files/7575427/README.md)

**Comment by katnatek** [comment]
Package updated to 1.8.2 version please update
[README.md](https://github.com/oleksis/youtube-dl-gui/files/7764660/README.md)

P.S. I don't want to open a issue per release, but if you request i'll do

**Comment by oleksis** [comment]
Thanks a lot. I hope find more help from the community for testing and Translations.

What you think about keep or drop support for Python 3.6 , because the End of Life is soon (23-december-2021)?

Thanks for the updates!

**Comment by katnatek** [comment]
> Thanks a lot. I hope find more help from the community for testing and Translations.
> 
> What you think about keep or drop support for Python 3.6 , because the End of Life is soon (23-december-2021)?
> 
Well in mageia 8 python is in 3.8 and in cauldron (development branch of mageia) is in 3.9 so mageia's users are not affected if you drop support for python 3.6

**Comment by katnatek** [comment]
Mageia package updated to 1.8.3 , please update README.md
[README.md](https://github.com/oleksis/youtube-dl-gui/files/8051220/README.md)

**Comment by katnatek** [comment]
Mageia package updated to 1.8.4 here is the README.md with the changes
[README.md](https://github.com/oleksis/youtube-dl-gui/files/10834900/README.md)

**Comment by oleksis** [comment]
The last version up to date is **1.8.5**

**Comment by katnatek** [comment]
Package and README.md updated to 1.8.5 ;)
[README.md](https://github.com/oleksis/youtube-dl-gui/files/10842267/README.md)
