### ISSUE TITLE
Feature request: set In and Out points for capture.

### ISSUE THREAD

**Issue by NeighNeighNeigh** [oleksis/youtube-dl-gui#8]
- [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dlg **1.0.0**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [x] Feature request (request for a new functionality)
- [ ] Question
- [ ] Other

---

### Feature request (request for a new functionality)

Please make sure that the requested feature is **NOT** already in the [TODO](https://github.com/oleksis/youtube-dl-gui/blob/master/TODO) list

- [x] I've **verified** and **i assure** that my requested feature is **NOT** in the TODO list

#### What operating system do you use ?

MacOS 10.15.7

---

### The request itself
Often we don't need to download the entire video. Please consider adding the ability to set In and Out points for capture. Here is [a detailed method](https://unix.stackexchange.com/a/388148) for doing so. Also thanks for the great work :)

**Comment by oleksis** [comment]
> ... Also thanks for the great work :)

Thanks for share you opinion and the words. Working in make YouTube-DL-GUI great again 🎉

**Comment by NeighNeighNeigh** [comment]
My pleasure, I'm so glad you're at the helm :)

**Comment by NeighNeighNeigh** [comment]
Any change of seeing progress on this issue?

**Comment by oleksis** [comment]
@NeighNeighNeigh I am trying to update and lay the foundations of the project so that maintenance will be "easier" in the future.  Once we opt for a stable version I can add new features to the GUI

Thank you for your patience!

**Comment by NeighNeighNeigh** [comment]
Okay cool, thanks for the update, I shall remain patient :)

**Comment by oleksis** [comment]
You can test the [Alpha Release on PyPi](https://test.pypi.org/project/yt-dlg/1.6.0a1/)
```bash
$ pip install -i https://test.pypi.org/simple/ yt-dlg==1.6.0a1
```

![yt-dlg_Clip-Multimedia_HLS_2](https://user-images.githubusercontent.com/44526468/120428530-cdebb800-c341-11eb-8f55-9786493ca51e.png)

![yt-dlg_Clip-Multimedia_HLS](https://user-images.githubusercontent.com/44526468/120428526-ccba8b00-c341-11eb-8609-b4d36f585cd0.png)

Any problem report the issue here o feel fre to open new. If all work Ok, letme know and Release the stable version

**Comment by NeighNeighNeigh** [comment]
I'm sorry I can't seem to get it installed. Having issues with PIP :(

**Comment by oleksis** [comment]
> I'm sorry I can't seem to get it installed. Having issues with PIP :(

I see you use MacOS. You can share the Logs when you try use pip from Test?

> Is it possible to get it elsewhere?
Other way is make the release and use the version for GNU/Linux🤔. I will like you test first and make the stable release.

**Comment by NeighNeighNeigh** [comment]
Sure this is the output from terminal:

ERROR: Could not find a version that satisfies the requirement wxPython<=4.1.1,>=4.0.7.post2 (from yt-dlg==1.6.0a1) (from versions: none)
ERROR: No matching distribution found for wxPython<=4.1.1,>=4.0.7.post2 (from yt-dlg==1.6.0a1)

**Comment by oleksis** [comment]
> Is it possible to get it elsewhere?

Try download the bundle for **GNU/Linux** from the site: https://oleksis.github.io/youtube-dl-gui/

**Comment by oleksis** [comment]
@NeighNeighNeigh you can check the [GNU/Linux last Release](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.6.0/yt-dlg) ?
