### ISSUE TITLE
Wrong sha256 sums in SHA2-256SUMS

### ISSUE THREAD

**Issue by nicolaasjan** [oleksis/youtube-dl-gui#9]
## Please follow the guide below

- You will be asked some questions and requested to provide some information, please read them **carefully** and answer **honestly**
- Put an `x` into all the boxes [ ] relevant to your issue (like that [x])
- Use *Preview* tab to see how your issue will actually look like

### WARNING
All invalid issues will be rejected!!

---

### Before going further

- If your problem is a bug with **youtube-dl** or a request for new site support please report it [here](https://github.com/rg3/youtube-dl/issues)

- Make sure you are using the *latest* **youtube-dlg** version (Click the `Settings` icon and then `About` to view the current version)

- Make sure you are using the *latest* **youtube-dl** version (Click the `Settings` icon and then `Update` to update to the latest **youtube-dl** version)

- Make sure you searched the bugtracker for similar issues **including closed ones**

- Make sure to read the [FAQs](https://github.com/oleksis/youtube-dl-gui/blob/master/docs/faqs.md) file

  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running youtube-dlg **1.1.4**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [ ] Question
- [x] Other

#### What operating system do you use ?
Linux Mint 19.3
#### List of actions to perform to reproduce the problem:

  1. Download `youtube-dlg` and `youtube-dlg.exe`.
  2. Verify the sha256 sums of both.
  3. Compare with [SHA2-256SUMS](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.1.4/SHA2-256SUMS).
  
#### What is the expected behaviour ?
They should match with [SHA2-256SUMS](https://github.com/oleksis/youtube-dl-gui/releases/download/v1.1.4/SHA2-256SUMS):

```
ea023f8753bc0a64a5d1e7489e84220918fc1d3a930cdb3507d6f01a28f227d8 youtube-dlg.exe
08ea60f751169a702d76a6ee6e34f2081a3d492104b9de98124b6e087536f77e youtube-dlg
```

#### What happens instead ?
They are in fact:

```
13096b8dc35ed53d5ca0b835e435f3b7431f957f91feeefe5f5172cf59ef8f4b youtube-dlg.exe
fa4c0c7eb02cf499f58821412c01d8cbf067baafa8a36077372dce3be0a00324 youtube-dlg
```

**Comment by nicolaasjan** [comment]
@pukkandan had a similar issue with [yt-dlp](https://github.com/yt-dlp/yt-dlp) and it was fixed with
https://github.com/yt-dlp/yt-dlp/commit/55e36f035cff0b7b75118930bb7bd03a75ffd534

**Comment by pukkandan** [comment]
This is an issue with github action's inbuilt SHA function. Use windows' own `Get-FileHash` to get the correct hash. See the abovementioned commit for implementation

**Comment by oleksis** [comment]
> @pukkandan had a similar issue with [yt-dlp](https://github.com/yt-dlp/yt-dlp) and it was fixed with
> [yt-dlp/yt-dlp@55e36f0](https://github.com/yt-dlp/yt-dlp/commit/55e36f035cff0b7b75118930bb7bd03a75ffd534)

@nicolaasjan and @pukkandan Thanks for the feedbacks and the help!!!

I try fix in this [commit](https://github.com/oleksis/youtube-dl-gui/commit/1c22845ec3c473a813d7cf5a2a8654df230702a8) and will work in the next release

**Comment by pukkandan** [comment]
@oleksis I would recommend cloning this to a private repo and testing the build process there to make sure that there are no bugs. this is what I do when changing GH actions

**Comment by DumbJoe** [comment]
So the reason was because of this: 
> * Hash calculation on Windows now uses PowerShell rather than the legacy certutil

What if you use a third party program? Or do they all piggey back off either certutil or powershell for hashing and the third party is just a front end gui?

**Comment by oleksis** [comment]
The checksum ([SHA2-256SUM](https://github.com/oleksis/youtube-dl-gui/blob/e1cd02cae475a451c92f158dd55afc9ab14071ad/.github/workflows/release.yml#L64)) is generated from GitHub Actions and on Windows uses `PowerShell` by default

**Comment by DumbJoe** [comment]
So all third party hashing programs uses PowerShell? Like HashMyFiles?
