### ISSUE TITLE
Which programs do I need to allow through my firewall?

### ISSUE THREAD

**Issue by Cantersoft** [oleksis/youtube-dl-gui#90]
---
  - [x] **I think** my problem is **NOT** with **youtube-dl**
  - [x] I've **verified** and **i assure** that I'm running yt-dlg **1.X.Y**
  - [x] **I assure** that i am using the latest version of **youtube-dl**
  - [x] [Searched](https://github.com/oleksis/youtube-dl-gui/issues) bugtracker
  - [x] I've read the FAQs file

---

### What is the purpose of your *issue*?

- [ ] Bug report
- [ ] Feature request (request for a new functionality)
- [x] Question
- [ ] Other

---

Do I need to allow any additional programs besides `yt-dlg.exe` through the firewall, or make any similar adjustments to my firewall so that this program is able to connect to the internet? I see `youtube-dl.exe` is used in the backend, so I wonder if the program gets automatically stored in an unspecified location on the disk.

The way it is right now, I have an outbound allow rule for `yt-dlg.exe` in Windows Defender Firewall, in Group Policy. However, downloads fail unless I turn the firewall off, or use `youtube-dl` without the interface.

**Comment by oleksis** [comment]
The setting and the CLI backends like `youtube-dl` and `yt-dlp` you can find in:

- Windows: `%APPDATA%/yt-dlg`
- GNU/Linux:`$HOME/.config/yt-dlg/`

Reed more in [this comment](https://github.com/oleksis/youtube-dl-gui/issues/80#issuecomment-1033236760)

**Comment by Cantersoft** [comment]
Thank you!
